/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rojo8' at '12/10/16 11:44 PM' with Gradle 2.13
 *
 * @author rojo8, @date 12/10/16 11:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
